theme: minima
title: Stephanie Kealey's Online Resume
author: Stephanie Kealey
email: slk216@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
 My name is Stephanie Kealey and I am a senior Computer Information Systems major 
 with a minor in Spanish. I will use this repository to display the skills and certifications 
 I acquired in my time at The University of Tulsa.

# social links
github_username:  stephkealey
linkedin_url: https://www.linkedin.com/in/stephanie-lynn-kealey/

show_excerpts: true # set to false to remove excerpts on the homepage
